﻿import { type LanguageCode, getSupportedLanguage } from '../../i18n/languages';

export interface OnboardingCopy {
  title: string;
  subtitle: string;
  stepAge: string;
  stepConsent: string;
  stepLogin: string;
  ageTitle: string;
  ageDesc: string;
  birthYearLabel: string;
  birthMonthLabel: string;
  ageNotice: string;
  languageLabel: string;
  consentTitle: string;
  consentDesc: string;
  consentSupport: string;
  consentChoiceNote: string;
  consentAll: string;
  terms: string;
  operation: string;
  privacy: string;
  ugc: string;
  adOptional: string;
  requiredLabel: string;
  optionalLabel: string;
  openPolicy: string;
  viewPolicyOnWeb: string;
  nextButton: string;
  backButton: string;
  loginTitle: string;
  loginDesc: string;
  loginButton: string;
  tooYoungTitle: string;
  tooYoungBody: string;
  invalidBirthTitle: string;
  invalidBirthBody: string;
  consentRequiredTitle: string;
  consentRequiredBody: string;
}

const BASE: OnboardingCopy = {
  title: 'Welcome to RPcore',
  subtitle: 'A calm, personalized space for AI story roleplay',
  stepAge: 'Age',
  stepConsent: 'Consent',
  stepLogin: 'Login',
  ageTitle: 'Age verification',
  ageDesc: 'Before you begin, we need to confirm that you are 17 or older.',
  birthYearLabel: 'Birth year',
  birthMonthLabel: 'Birth month',
  ageNotice: 'Please continue only if you are 17 or older.',
  languageLabel: 'Language',
  consentTitle: 'A few things to review first',
  consentDesc: 'Read the required items and choose what feels right before you continue.',
  consentSupport: 'Optional items can be changed later, and basic service is still available without them.',
  consentChoiceNote: 'You can reopen each policy anytime before you decide.',
  consentAll: 'Select all items at once',
  terms: 'Terms of service',
  operation: 'Operation policy',
  privacy: 'Privacy policy',
  ugc: 'UGC and creator terms',
  adOptional: 'Personalized ads and recommendations',
  requiredLabel: 'Required',
  optionalLabel: 'Optional',
  openPolicy: 'Open',
  viewPolicyOnWeb: 'View details on the web',
  nextButton: 'Continue',
  backButton: 'Back',
  loginTitle: 'One last step',
  loginDesc: 'Sign in to save your profile, sync your choices, and continue smoothly across sessions.',
  loginButton: 'Continue with Google',
  tooYoungTitle: 'Age restriction',
  tooYoungBody: 'This app is available only for users aged 17 and older.',
  invalidBirthTitle: 'Invalid birth date',
  invalidBirthBody: 'Please enter a valid year and month.',
  consentRequiredTitle: 'Required items still need your review',
  consentRequiredBody: 'Please review the required items and complete your choices to continue.' };

const COPY_OVERRIDES: Partial<Record<LanguageCode, OnboardingCopy>> = {
  ko: {
    title: 'RPcore에 오신 걸 환영합니다',
    subtitle: '안심하고 몰입하는 AI 스토리 플레이',
    stepAge: '나이',
    stepConsent: '확인',
    stepLogin: '로그인',
    ageTitle: '나이 확인',
    ageDesc: '시작하기 전에 만 17세 이상인지 먼저 확인할게요.',
    birthYearLabel: '출생 연도',
    birthMonthLabel: '출생 월',
    ageNotice: '계속하려면 만 17세 이상인지 확인해 주세요.',
    languageLabel: '언어',
    consentTitle: '시작 전에 먼저 확인해 주세요',
    consentDesc: '필수 항목을 읽고, 직접 검토한 뒤 선택을 마치면 계속할 수 있어요.',
    consentSupport: '선택 항목은 나중에 언제든 바꿀 수 있고, 동의하지 않아도 기본 서비스는 이용할 수 있어요.',
    consentChoiceNote: '결정하기 전에도 각 정책을 언제든 다시 열어볼 수 있어요.',
    consentAll: '모두 동의하기',
    terms: '이용약관',
    operation: '운영 정책',
    privacy: '개인정보처리방침',
    ugc: 'UGC 및 크리에이터 약관',
    adOptional: '맞춤형 광고 및 추천',
    requiredLabel: '필수',
    optionalLabel: '선택',
    openPolicy: '열기',
    viewPolicyOnWeb: '웹에서 자세히 보기',
    nextButton: '다음으로',
    backButton: '이전',
    loginTitle: '마지막 한 단계',
    loginDesc: '로그인하면 프로필과 선택 내용을 저장하고, 다음에도 같은 흐름으로 이어서 이용할 수 있어요.',
    loginButton: 'Google로 계속하기',
    tooYoungTitle: '나이 제한',
    tooYoungBody: '이 앱은 만 17세 이상만 사용할 수 있어요.',
    invalidBirthTitle: '잘못된 생년월일',
    invalidBirthBody: '유효한 연도와 월을 입력해 주세요.',
    consentRequiredTitle: '필수 항목을 먼저 확인해 주세요',
    consentRequiredBody: '계속하려면 필수 항목을 읽고 선택을 완료해 주세요.' },
  ja: {
    title: 'RPcoreへようこそ',
    subtitle: '落ち着いて没入できるAIストーリーロールプレイ',
    stepAge: '年齢',
    stepConsent: '確認',
    stepLogin: 'ログイン',
    ageTitle: '年齢確認',
    ageDesc: '開始前に、17歳以上であることを確認します。',
    birthYearLabel: '生年',
    birthMonthLabel: '誕生月',
    ageNotice: '17歳以上であることを確認してから続行してください。',
    languageLabel: '言語',
    consentTitle: '最初に確認してください',
    consentDesc: '必須項目を読み、内容を確認したうえで選択してから続行してください。',
    consentSupport: '任意項目は後から変更でき、同意しなくても基本サービスは利用できます。',
    consentChoiceNote: '決める前に、各ポリシーをいつでも開き直せます。',
    consentAll: 'すべて一度に選択',
    terms: '利用規約',
    operation: '運営ポリシー',
    privacy: 'プライバシーポリシー',
    ugc: 'UGC・クリエイター規約',
    adOptional: 'パーソナライズ広告とおすすめ',
    requiredLabel: '必須',
    optionalLabel: '任意',
    openPolicy: '開く',
    viewPolicyOnWeb: 'Webで詳しく見る',
    nextButton: '次へ',
    backButton: '戻る',
    loginTitle: 'あと一歩です',
    loginDesc: 'サインインすると、プロフィールと選択内容を保存し、次回もそのまま続けられます。',
    loginButton: 'Googleで続行',
    tooYoungTitle: '年齢制限',
    tooYoungBody: 'このアプリは17歳以上の方のみ利用できます。',
    invalidBirthTitle: '生年月日が正しくありません',
    invalidBirthBody: '有効な年と月を入力してください。',
    consentRequiredTitle: '必須項目を先に確認してください',
    consentRequiredBody: '続行するには、必須項目を確認して選択を完了してください。' },
  'zh-CN': {
    title: '欢迎来到 RPcore',
    subtitle: '安心沉浸的 AI 故事角色扮演空间',
    stepAge: '年龄',
    stepConsent: '确认',
    stepLogin: '登录',
    ageTitle: '年龄验证',
    ageDesc: '开始前，我们需要先确认你已年满 17 岁。',
    birthYearLabel: '出生年份',
    birthMonthLabel: '出生月份',
    ageNotice: '请在确认自己已满 17 岁后继续。',
    languageLabel: '语言',
    consentTitle: '开始前请先查看',
    consentDesc: '请先阅读必选项目，并在完成选择后继续。',
    consentSupport: '可选项目之后也能修改，不同意也可以使用基础服务。',
    consentChoiceNote: '在决定之前，你随时都可以重新查看各项政策。',
    consentAll: '一次选择全部项目',
    terms: '服务条款',
    operation: '运营政策',
    privacy: '隐私政策',
    ugc: 'UGC 与创作者条款',
    adOptional: '个性化广告与推荐',
    requiredLabel: '必选',
    optionalLabel: '可选',
    openPolicy: '打开',
    viewPolicyOnWeb: '在网页查看详情',
    nextButton: '继续',
    backButton: '返回',
    loginTitle: '最后一步',
    loginDesc: '登录后可保存你的资料与选择，并在不同会话间顺畅继续。',
    loginButton: '使用 Google 继续',
    tooYoungTitle: '年龄限制',
    tooYoungBody: '本应用仅限 17 岁及以上用户使用。',
    invalidBirthTitle: '出生日期无效',
    invalidBirthBody: '请输入有效的年份和月份。',
    consentRequiredTitle: '请先完成必选项目',
    consentRequiredBody: '继续前，请先查看必选项目并完成你的选择。' },
  'zh-TW': {
    title: '歡迎來到 RPcore',
    subtitle: '安心沉浸的 AI 故事角色扮演空間',
    stepAge: '年齡',
    stepConsent: '確認',
    stepLogin: '登入',
    ageTitle: '年齡驗證',
    ageDesc: '開始前，我們需要先確認你已滿 17 歲。',
    birthYearLabel: '出生年份',
    birthMonthLabel: '出生月份',
    ageNotice: '請先確認自己已滿 17 歲後再繼續。',
    languageLabel: '語言',
    consentTitle: '開始前請先查看',
    consentDesc: '請先閱讀必選項目，完成你的選擇後再繼續。',
    consentSupport: '可選項目之後也能修改，不同意也可以使用基本服務。',
    consentChoiceNote: '在決定之前，你隨時都可以重新查看各項政策。',
    consentAll: '一次選取全部項目',
    terms: '服務條款',
    operation: '營運政策',
    privacy: '隱私政策',
    ugc: 'UGC 與創作者條款',
    adOptional: '個人化廣告與推薦',
    requiredLabel: '必選',
    optionalLabel: '可選',
    openPolicy: '開啟',
    viewPolicyOnWeb: '在網頁查看詳情',
    nextButton: '繼續',
    backButton: '返回',
    loginTitle: '最後一步',
    loginDesc: '登入後可儲存你的資料與選擇，並在不同階段順暢接續。',
    loginButton: '使用 Google 繼續',
    tooYoungTitle: '年齡限制',
    tooYoungBody: '本應用僅限 17 歲以上使用者使用。',
    invalidBirthTitle: '出生日期無效',
    invalidBirthBody: '請輸入有效的年份與月份。',
    consentRequiredTitle: '請先完成必選項目',
    consentRequiredBody: '繼續前，請先查看必選項目並完成你的選擇。' },
  es: {
    title: 'Bienvenido a RPcore',
    subtitle: 'Un espacio tranquilo para roleplay de historias con IA',
    stepAge: 'Edad',
    stepConsent: 'Revisión',
    stepLogin: 'Inicio',
    ageTitle: 'Verificación de edad',
    ageDesc: 'Antes de empezar, necesitamos confirmar que tienes 17 años o más.',
    birthYearLabel: 'Año de nacimiento',
    birthMonthLabel: 'Mes de nacimiento',
    ageNotice: 'Continúa solo si tienes 17 años o más.',
    languageLabel: 'Idioma',
    consentTitle: 'Hay algunas cosas para revisar primero',
    consentDesc: 'Lee los elementos obligatorios y completa tu elección antes de continuar.',
    consentSupport: 'Los elementos opcionales se pueden cambiar después y el servicio básico sigue disponible sin aceptarlos.',
    consentChoiceNote: 'Puedes volver a abrir cada política cuando quieras antes de decidir.',
    consentAll: 'Seleccionar todo de una vez',
    terms: 'Términos del servicio',
    operation: 'Política de operación',
    privacy: 'Política de privacidad',
    ugc: 'Términos de UGC y creadores',
    adOptional: 'Anuncios y recomendaciones personalizados',
    requiredLabel: 'Obligatorio',
    optionalLabel: 'Opcional',
    openPolicy: 'Abrir',
    viewPolicyOnWeb: 'Ver detalles en la web',
    nextButton: 'Continuar',
    backButton: 'Atrás',
    loginTitle: 'Un último paso',
    loginDesc: 'Inicia sesión para guardar tu perfil y tus elecciones, y seguir sin problemas en otras sesiones.',
    loginButton: 'Continuar con Google',
    tooYoungTitle: 'Restricción de edad',
    tooYoungBody: 'Esta aplicación solo está disponible para usuarios de 17 años o más.',
    invalidBirthTitle: 'Fecha de nacimiento no válida',
    invalidBirthBody: 'Ingresa un año y un mes válidos.',
    consentRequiredTitle: 'Primero revisa los elementos obligatorios',
    consentRequiredBody: 'Para continuar, revisa los elementos obligatorios y completa tu elección.' },
  pt: {
    title: 'Bem-vindo ao RPcore',
    subtitle: 'Um espaço calmo para roleplay de histórias com IA',
    stepAge: 'Idade',
    stepConsent: 'Revisão',
    stepLogin: 'Login',
    ageTitle: 'Verificação de idade',
    ageDesc: 'Antes de começar, precisamos confirmar que você tem 17 anos ou mais.',
    birthYearLabel: 'Ano de nascimento',
    birthMonthLabel: 'Mês de nascimento',
    ageNotice: 'Continue apenas se você tiver 17 anos ou mais.',
    languageLabel: 'Idioma',
    consentTitle: 'Alguns pontos para revisar primeiro',
    consentDesc: 'Leia os itens obrigatórios e finalize sua escolha antes de continuar.',
    consentSupport: 'Os itens opcionais podem ser alterados depois, e o serviço básico continua disponível sem eles.',
    consentChoiceNote: 'Você pode abrir cada política novamente quando quiser antes de decidir.',
    consentAll: 'Selecionar tudo de uma vez',
    terms: 'Termos de serviço',
    operation: 'Política de operação',
    privacy: 'Política de privacidade',
    ugc: 'Termos de UGC e criadores',
    adOptional: 'Anúncios e recomendações personalizados',
    requiredLabel: 'Obrigatório',
    optionalLabel: 'Opcional',
    openPolicy: 'Abrir',
    viewPolicyOnWeb: 'Ver detalhes na web',
    nextButton: 'Continuar',
    backButton: 'Voltar',
    loginTitle: 'Só falta mais um passo',
    loginDesc: 'Entre para salvar seu perfil e suas escolhas, e continuar sem interrupções em outras sessões.',
    loginButton: 'Continuar com Google',
    tooYoungTitle: 'Restrição de idade',
    tooYoungBody: 'Este app está disponível apenas para usuários com 17 anos ou mais.',
    invalidBirthTitle: 'Data de nascimento inválida',
    invalidBirthBody: 'Informe um ano e um mês válidos.',
    consentRequiredTitle: 'Revise primeiro os itens obrigatórios',
    consentRequiredBody: 'Para continuar, revise os itens obrigatórios e conclua sua escolha.' },
  fr: {
    title: 'Bienvenue sur RPcore',
    subtitle: 'Un espace calme pour le roleplay narratif avec IA',
    stepAge: 'Âge',
    stepConsent: 'Révision',
    stepLogin: 'Connexion',
    ageTitle: 'Vérification de l’âge',
    ageDesc: 'Avant de commencer, nous devons confirmer que vous avez au moins 17 ans.',
    birthYearLabel: 'Année de naissance',
    birthMonthLabel: 'Mois de naissance',
    ageNotice: 'Veuillez continuer uniquement si vous avez 17 ans ou plus.',
    languageLabel: 'Langue',
    consentTitle: 'Quelques points à vérifier d’abord',
    consentDesc: 'Lisez les éléments obligatoires et terminez votre choix avant de continuer.',
    consentSupport: 'Les éléments facultatifs peuvent être modifiés plus tard, et le service de base reste disponible sans eux.',
    consentChoiceNote: 'Vous pouvez rouvrir chaque politique à tout moment avant de décider.',
    consentAll: 'Tout sélectionner en une fois',
    terms: 'Conditions d’utilisation',
    operation: 'Politique d’exploitation',
    privacy: 'Politique de confidentialité',
    ugc: 'Conditions UGC et créateurs',
    adOptional: 'Publicités et recommandations personnalisées',
    requiredLabel: 'Obligatoire',
    optionalLabel: 'Facultatif',
    openPolicy: 'Ouvrir',
    viewPolicyOnWeb: 'Voir les détails sur le web',
    nextButton: 'Continuer',
    backButton: 'Retour',
    loginTitle: 'Encore une étape',
    loginDesc: 'Connectez-vous pour enregistrer votre profil et vos choix, puis reprendre facilement plus tard.',
    loginButton: 'Continuer avec Google',
    tooYoungTitle: 'Restriction d’âge',
    tooYoungBody: 'Cette application est réservée aux utilisateurs de 17 ans et plus.',
    invalidBirthTitle: 'Date de naissance invalide',
    invalidBirthBody: 'Veuillez saisir une année et un mois valides.',
    consentRequiredTitle: 'Veuillez d’abord vérifier les éléments obligatoires',
    consentRequiredBody: 'Pour continuer, vérifiez les éléments obligatoires et terminez votre choix.' },
  de: {
    title: 'Willkommen bei RPcore',
    subtitle: 'Ein ruhiger Raum für KI-Story-Rollenspiel',
    stepAge: 'Alter',
    stepConsent: 'Prüfung',
    stepLogin: 'Login',
    ageTitle: 'Altersprüfung',
    ageDesc: 'Bevor du beginnst, müssen wir bestätigen, dass du mindestens 17 Jahre alt bist.',
    birthYearLabel: 'Geburtsjahr',
    birthMonthLabel: 'Geburtsmonat',
    ageNotice: 'Bitte fahre nur fort, wenn du 17 Jahre oder älter bist.',
    languageLabel: 'Sprache',
    consentTitle: 'Bitte zuerst kurz prüfen',
    consentDesc: 'Lies die Pflichtpunkte und schließe deine Auswahl ab, bevor du fortfährst.',
    consentSupport: 'Optionale Punkte kannst du später ändern, und der Basisdienst bleibt auch ohne sie verfügbar.',
    consentChoiceNote: 'Du kannst jede Richtlinie vor deiner Entscheidung jederzeit erneut öffnen.',
    consentAll: 'Alles auf einmal auswählen',
    terms: 'Nutzungsbedingungen',
    operation: 'Betriebsrichtlinie',
    privacy: 'Datenschutzrichtlinie',
    ugc: 'UGC- und Creator-Bedingungen',
    adOptional: 'Personalisierte Werbung und Empfehlungen',
    requiredLabel: 'Pflicht',
    optionalLabel: 'Optional',
    openPolicy: 'Öffnen',
    viewPolicyOnWeb: 'Details im Web ansehen',
    nextButton: 'Weiter',
    backButton: 'Zurück',
    loginTitle: 'Noch ein Schritt',
    loginDesc: 'Melde dich an, um dein Profil und deine Auswahl zu speichern und später nahtlos weiterzumachen.',
    loginButton: 'Mit Google fortfahren',
    tooYoungTitle: 'Altersbeschränkung',
    tooYoungBody: 'Diese App ist nur für Nutzer ab 17 Jahren verfügbar.',
    invalidBirthTitle: 'Ungültiges Geburtsdatum',
    invalidBirthBody: 'Bitte gib ein gültiges Jahr und einen gültigen Monat ein.',
    consentRequiredTitle: 'Bitte prüfe zuerst die Pflichtpunkte',
    consentRequiredBody: 'Um fortzufahren, prüfe die Pflichtpunkte und schließe deine Auswahl ab.' },
  it: {
    title: 'Benvenuto su RPcore',
    subtitle: 'Uno spazio tranquillo per il roleplay narrativo con IA',
    stepAge: 'Età',
    stepConsent: 'Verifica',
    stepLogin: 'Accesso',
    ageTitle: 'Verifica dell’età',
    ageDesc: 'Prima di iniziare, dobbiamo confermare che tu abbia almeno 17 anni.',
    birthYearLabel: 'Anno di nascita',
    birthMonthLabel: 'Mese di nascita',
    ageNotice: 'Continua solo se hai almeno 17 anni.',
    languageLabel: 'Lingua',
    consentTitle: 'Ci sono alcune cose da controllare prima',
    consentDesc: 'Leggi gli elementi obbligatori e completa la tua scelta prima di continuare.',
    consentSupport: 'Gli elementi opzionali possono essere modificati in seguito e il servizio base resta disponibile anche senza di essi.',
    consentChoiceNote: 'Puoi riaprire ogni informativa quando vuoi prima di decidere.',
    consentAll: 'Seleziona tutto in una volta',
    terms: 'Termini di servizio',
    operation: 'Politica operativa',
    privacy: 'Informativa sulla privacy',
    ugc: 'Termini UGC e creator',
    adOptional: 'Annunci e consigli personalizzati',
    requiredLabel: 'Obbligatorio',
    optionalLabel: 'Opzionale',
    openPolicy: 'Apri',
    viewPolicyOnWeb: 'Vedi i dettagli sul web',
    nextButton: 'Continua',
    backButton: 'Indietro',
    loginTitle: 'Manca solo un passo',
    loginDesc: 'Accedi per salvare il tuo profilo e le tue scelte e continuare senza interruzioni nelle prossime sessioni.',
    loginButton: 'Continua con Google',
    tooYoungTitle: 'Limite di età',
    tooYoungBody: 'Questa app è disponibile solo per utenti di almeno 17 anni.',
    invalidBirthTitle: 'Data di nascita non valida',
    invalidBirthBody: 'Inserisci un anno e un mese validi.',
    consentRequiredTitle: 'Controlla prima gli elementi obbligatori',
    consentRequiredBody: 'Per continuare, verifica gli elementi obbligatori e completa la tua scelta.' },
  ru: {
    title: 'Добро пожаловать в RPcore',
    subtitle: 'Спокойное пространство для сюжетного ролевого общения с ИИ',
    stepAge: 'Возраст',
    stepConsent: 'Проверка',
    stepLogin: 'Вход',
    ageTitle: 'Проверка возраста',
    ageDesc: 'Перед началом нам нужно подтвердить, что вам исполнилось 17 лет.',
    birthYearLabel: 'Год рождения',
    birthMonthLabel: 'Месяц рождения',
    ageNotice: 'Продолжайте, только если вам уже есть 17 лет.',
    languageLabel: 'Язык',
    consentTitle: 'Сначала нужно кое-что проверить',
    consentDesc: 'Прочитайте обязательные пункты и завершите свой выбор перед продолжением.',
    consentSupport: 'Необязательные пункты можно изменить позже, а базовый сервис доступен и без них.',
    consentChoiceNote: 'Вы можете снова открыть любую политику в любой момент до принятия решения.',
    consentAll: 'Выбрать все сразу',
    terms: 'Условия использования',
    operation: 'Правила сервиса',
    privacy: 'Политика конфиденциальности',
    ugc: 'Условия UGC и авторов',
    adOptional: 'Персонализированная реклама и рекомендации',
    requiredLabel: 'Обязательно',
    optionalLabel: 'Необязательно',
    openPolicy: 'Открыть',
    viewPolicyOnWeb: 'Открыть подробности на сайте',
    nextButton: 'Продолжить',
    backButton: 'Назад',
    loginTitle: 'Остался последний шаг',
    loginDesc: 'Войдите, чтобы сохранить профиль и ваши выборы и без проблем продолжить позже.',
    loginButton: 'Продолжить через Google',
    tooYoungTitle: 'Возрастное ограничение',
    tooYoungBody: 'Это приложение доступно только пользователям от 17 лет.',
    invalidBirthTitle: 'Неверная дата рождения',
    invalidBirthBody: 'Введите корректные год и месяц.',
    consentRequiredTitle: 'Сначала проверьте обязательные пункты',
    consentRequiredBody: 'Чтобы продолжить, проверьте обязательные пункты и завершите свой выбор.' },
  th: {
    title: 'ยินดีต้อนรับสู่ RPcore',
    subtitle: 'พื้นที่สบาย ๆ สำหรับโรลเพลย์เรื่องราวกับ AI',
    stepAge: 'อายุ',
    stepConsent: 'ตรวจสอบ',
    stepLogin: 'เข้าสู่ระบบ',
    ageTitle: 'ยืนยันอายุ',
    ageDesc: 'ก่อนเริ่มใช้งาน เราจำเป็นต้องยืนยันว่าคุณมีอายุ 17 ปีขึ้นไป',
    birthYearLabel: 'ปีเกิด',
    birthMonthLabel: 'เดือนเกิด',
    ageNotice: 'โปรดดำเนินการต่อเมื่อคุณมีอายุ 17 ปีขึ้นไปเท่านั้น',
    languageLabel: 'ภาษา',
    consentTitle: 'มีบางอย่างที่ต้องตรวจสอบก่อน',
    consentDesc: 'อ่านรายการที่จำเป็นและเลือกให้เรียบร้อยก่อนดำเนินการต่อ',
    consentSupport: 'รายการเพิ่มเติมสามารถเปลี่ยนได้ภายหลัง และยังใช้บริการพื้นฐานได้แม้ไม่ยินยอม',
    consentChoiceNote: 'คุณสามารถเปิดนโยบายแต่ละรายการดูอีกครั้งได้ทุกเมื่อก่อนตัดสินใจ',
    consentAll: 'เลือกทั้งหมดในครั้งเดียว',
    terms: 'ข้อกำหนดการให้บริการ',
    operation: 'นโยบายการดำเนินงาน',
    privacy: 'นโยบายความเป็นส่วนตัว',
    ugc: 'ข้อกำหนด UGC และผู้สร้าง',
    adOptional: 'โฆษณาและคำแนะนำแบบเฉพาะบุคคล',
    requiredLabel: 'จำเป็น',
    optionalLabel: 'ไม่บังคับ',
    openPolicy: 'เปิด',
    viewPolicyOnWeb: 'ดูรายละเอียดบนเว็บ',
    nextButton: 'ต่อไป',
    backButton: 'ย้อนกลับ',
    loginTitle: 'เหลืออีกขั้นตอนเดียว',
    loginDesc: 'เข้าสู่ระบบเพื่อบันทึกโปรไฟล์และตัวเลือกของคุณ และใช้งานต่อได้อย่างราบรื่นในครั้งถัดไป',
    loginButton: 'ดำเนินการต่อด้วย Google',
    tooYoungTitle: 'จำกัดอายุ',
    tooYoungBody: 'แอปนี้ใช้ได้เฉพาะผู้ที่มีอายุ 17 ปีขึ้นไป',
    invalidBirthTitle: 'วันเกิดไม่ถูกต้อง',
    invalidBirthBody: 'โปรดกรอกปีและเดือนที่ถูกต้อง',
    consentRequiredTitle: 'โปรดตรวจสอบรายการที่จำเป็นก่อน',
    consentRequiredBody: 'หากต้องการดำเนินการต่อ โปรดอ่านรายการที่จำเป็นและเลือกให้เสร็จสิ้น' },
  tr: {
    title: 'RPcore’a hoş geldiniz',
    subtitle: 'YZ hikâye rol yapma için sakin bir alan',
    stepAge: 'Yaş',
    stepConsent: 'İnceleme',
    stepLogin: 'Giriş',
    ageTitle: 'Yaş doğrulama',
    ageDesc: 'Başlamadan önce 17 yaşında veya daha büyük olduğunuzu doğrulamamız gerekiyor.',
    birthYearLabel: 'Doğum yılı',
    birthMonthLabel: 'Doğum ayı',
    ageNotice: 'Lütfen yalnızca 17 yaşında veya daha büyükseniz devam edin.',
    languageLabel: 'Dil',
    consentTitle: 'Önce gözden geçirmeniz gereken birkaç şey var',
    consentDesc: 'Zorunlu öğeleri okuyup seçiminizi tamamladıktan sonra devam edin.',
    consentSupport: 'İsteğe bağlı öğeler daha sonra değiştirilebilir ve bunlar olmadan da temel hizmet kullanılabilir.',
    consentChoiceNote: 'Karar vermeden önce her politikayı istediğiniz zaman yeniden açabilirsiniz.',
    consentAll: 'Tümünü tek seferde seç',
    terms: 'Hizmet şartları',
    operation: 'İşletim politikası',
    privacy: 'Gizlilik politikası',
    ugc: 'UGC ve içerik üretici şartları',
    adOptional: 'Kişiselleştirilmiş reklamlar ve öneriler',
    requiredLabel: 'Zorunlu',
    optionalLabel: 'İsteğe bağlı',
    openPolicy: 'Aç',
    viewPolicyOnWeb: 'Ayrıntıları webde görüntüle',
    nextButton: 'Devam et',
    backButton: 'Geri',
    loginTitle: 'Son bir adım kaldı',
    loginDesc: 'Profilinizi ve seçimlerinizi kaydetmek ve daha sonra sorunsuz devam etmek için giriş yapın.',
    loginButton: 'Google ile devam et',
    tooYoungTitle: 'Yaş sınırı',
    tooYoungBody: 'Bu uygulama yalnızca 17 yaş ve üzerindeki kullanıcılar içindir.',
    invalidBirthTitle: 'Geçersiz doğum tarihi',
    invalidBirthBody: 'Lütfen geçerli bir yıl ve ay girin.',
    consentRequiredTitle: 'Önce zorunlu öğeleri inceleyin',
    consentRequiredBody: 'Devam etmek için zorunlu öğeleri gözden geçirip seçiminizi tamamlayın.' },
  hi: {
    title: 'RPcore में आपका स्वागत है',
    subtitle: 'AI स्टोरी रोलप्ले के लिए एक शांत और निजी जगह',
    stepAge: 'आयु',
    stepConsent: 'समीक्षा',
    stepLogin: 'लॉगिन',
    ageTitle: 'आयु सत्यापन',
    ageDesc: 'शुरू करने से पहले हमें यह पुष्टि करनी है कि आपकी आयु 17 वर्ष या उससे अधिक है।',
    birthYearLabel: 'जन्म वर्ष',
    birthMonthLabel: 'जन्म महीना',
    ageNotice: 'कृपया तभी आगे बढ़ें जब आपकी आयु 17 वर्ष या उससे अधिक हो।',
    languageLabel: 'भाषा',
    consentTitle: 'पहले कुछ बातें देख लें',
    consentDesc: 'आगे बढ़ने से पहले आवश्यक आइटम पढ़ें और अपना चयन पूरा करें।',
    consentSupport: 'वैकल्पिक आइटम बाद में बदले जा सकते हैं, और उनके बिना भी मूल सेवा उपलब्ध रहती है।',
    consentChoiceNote: 'निर्णय लेने से पहले आप किसी भी नीति को कभी भी फिर से खोल सकते हैं।',
    consentAll: 'सभी आइटम एक साथ चुनें',
    terms: 'सेवा की शर्तें',
    operation: 'संचालन नीति',
    privacy: 'गोपनीयता नीति',
    ugc: 'UGC और क्रिएटर शर्तें',
    adOptional: 'व्यक्तिगत विज्ञापन और सिफारिशें',
    requiredLabel: 'आवश्यक',
    optionalLabel: 'वैकल्पिक',
    openPolicy: 'खोलें',
    viewPolicyOnWeb: 'वेब पर विवरण देखें',
    nextButton: 'जारी रखें',
    backButton: 'वापस',
    loginTitle: 'बस एक आख़िरी चरण',
    loginDesc: 'अपना प्रोफ़ाइल और चयन सहेजने के लिए लॉगिन करें, ताकि अगली बार आसानी से जारी रख सकें।',
    loginButton: 'Google के साथ जारी रखें',
    tooYoungTitle: 'आयु सीमा',
    tooYoungBody: 'यह ऐप केवल 17 वर्ष या उससे अधिक आयु के उपयोगकर्ताओं के लिए उपलब्ध है।',
    invalidBirthTitle: 'अमान्य जन्मतिथि',
    invalidBirthBody: 'कृपया सही वर्ष और महीना दर्ज करें।',
    consentRequiredTitle: 'पहले आवश्यक आइटम देखें',
    consentRequiredBody: 'आगे बढ़ने के लिए आवश्यक आइटम पढ़ें और अपना चयन पूरा करें।' },
  ar: {
    title: 'مرحبًا بك في RPcore',
    subtitle: 'مساحة هادئة ومخصصة للعب الأدوار القصصي بالذكاء الاصطناعي',
    stepAge: 'العمر',
    stepConsent: 'المراجعة',
    stepLogin: 'تسجيل الدخول',
    ageTitle: 'التحقق من العمر',
    ageDesc: 'قبل البدء، نحتاج إلى التأكد من أنك تبلغ 17 عامًا أو أكثر.',
    birthYearLabel: 'سنة الميلاد',
    birthMonthLabel: 'شهر الميلاد',
    ageNotice: 'يرجى المتابعة فقط إذا كان عمرك 17 عامًا أو أكثر.',
    languageLabel: 'اللغة',
    consentTitle: 'هناك بعض الأمور لمراجعتها أولًا',
    consentDesc: 'اقرأ البنود المطلوبة وأكمل اختيارك قبل المتابعة.',
    consentSupport: 'يمكن تغيير البنود الاختيارية لاحقًا، كما أن الخدمة الأساسية متاحة حتى بدونها.',
    consentChoiceNote: 'يمكنك إعادة فتح كل سياسة في أي وقت قبل اتخاذ قرارك.',
    consentAll: 'تحديد جميع البنود دفعة واحدة',
    terms: 'شروط الخدمة',
    operation: 'سياسة التشغيل',
    privacy: 'سياسة الخصوصية',
    ugc: 'شروط المحتوى الذي ينشئه المستخدم والمبدعين',
    adOptional: 'الإعلانات والتوصيات المخصصة',
    requiredLabel: 'مطلوب',
    optionalLabel: 'اختياري',
    openPolicy: 'فتح',
    viewPolicyOnWeb: 'عرض التفاصيل على الويب',
    nextButton: 'متابعة',
    backButton: 'رجوع',
    loginTitle: 'تبقت خطوة واحدة',
    loginDesc: 'سجّل الدخول لحفظ ملفك الشخصي واختياراتك، ومتابعة الاستخدام بسلاسة لاحقًا.',
    loginButton: 'المتابعة باستخدام Google',
    tooYoungTitle: 'قيود العمر',
    tooYoungBody: 'هذا التطبيق متاح فقط للمستخدمين الذين تبلغ أعمارهم 17 عامًا أو أكثر.',
    invalidBirthTitle: 'تاريخ ميلاد غير صالح',
    invalidBirthBody: 'يرجى إدخال سنة وشهر صالحين.',
    consentRequiredTitle: 'يرجى مراجعة البنود المطلوبة أولًا',
    consentRequiredBody: 'للمتابعة، راجع البنود المطلوبة وأكمل اختيارك.' } };

export function getOnboardingCopy(lang: LanguageCode): OnboardingCopy {
  const supported = getSupportedLanguage(lang);
  return COPY_OVERRIDES[supported] ?? BASE;
}
