// TouchableOpacity aliased to PressableOpacity
import { useCallback, useEffect, useRef, useState } from 'react';
import { View, Text, StyleSheet, StatusBar, TextInput } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';

import { PressableOpacity as TouchableOpacity } from '../../components/PressableOpacity';
import Animated, { FadeIn, FadeInDown, useSharedValue, useAnimatedStyle, withSpring, withTiming, withSequence, interpolate } from 'react-native-reanimated';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BookOpen, CheckCircle } from 'lucide-react-native';

import { Space, Radius, Typography, Typo } from '../../constants/tokens';
const _W_border1 = '#181820';
import { ToastService } from '../../components/Toast';
import { useAuthStore } from '../../store/authStore';
import { useLanguageStore } from '../../store/languageStore';
import { getWebNovel } from '../../utils/webNovelStorage';
import { saveCommunityNovelPost } from '../../utils/communityNovelStore';
import { NovelAPI } from '../../api/NovelAPI';
import { PremiumBackdrop } from '../../components/ui/PremiumSurface';
import { PremiumHeroCard } from '../../components/ui/PremiumHeroCard';
import { NovelEditor } from '../../components/novel/NovelEditor';
import { useShallow } from 'zustand/react/shallow';
import type { ScreenProps } from '../../types/navigation';

function AnimatedInput({ style, containerStyle, ...props }: import('react-native').TextInputProps & { containerStyle?: import('react-native').ViewStyle }) {
  const focusProgress = useSharedValue(0);
  const borderStyle = useAnimatedStyle(() => ({
    borderColor: focusProgress.value > 0 ? `rgba(212,168,83,${0.35 + focusProgress.value * 0.3})` : _W_border1,
    shadowRadius: interpolate(focusProgress.value, [0, 1], [0, 10])
  }));

  return (
    <Animated.View style={[styles.inputWrap, borderStyle, containerStyle]}>
      <TextInput
        {...props}
        onFocus={(event: any) => {
          focusProgress.value = withTiming(1, { duration: 200 });
          props.onFocus?.(event);
        }}
        onBlur={(event: any) => {
          focusProgress.value = withTiming(0, { duration: 200 });
          props.onBlur?.(event);
        }}
        style={[styles.inputInner, style]}
        placeholderTextColor={'#797990'}
      />
    </Animated.View>
  );
}

export function WriteNovelPostScreen({ route, navigation }: ScreenProps<'WriteNovelPost'>) {
  const { novelId, novelTitle, novelPreview = '' } = route.params ?? {};
  const insets = useSafeAreaInsets();
  const user = useAuthStore(state => state.user);
  const { currentLanguage, t } = useLanguageStore(
    useShallow((s) => ({
      currentLanguage: s.currentLanguage,
        t: s.t
  })),
  );

  const [title, setTitle] = useState(novelTitle ?? '');
  const [content, setContent] = useState('');
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState('');
  const [posting, setPosting] = useState(false);
  const [posted, setPosted] = useState(false);
  const [postedNovelId, setPostedNovelId] = useState('');

  const isMountedRef = useRef(true);
  useEffect(() => {
    isMountedRef.current = true;
    return () => {
      isMountedRef.current = false;
    };
  }, []);

  const buttonScale = useSharedValue(1);
  const buttonStyle = useAnimatedStyle(() => ({ transform: [{ scale: buttonScale.value }] }));

  const labels = {
    titleRequired: t?.titleRequired ?? '',
    contentRequired: t?.contentRequired ?? '',
    postFailed: t?.errorOccurred ?? '',
    postSuccess: t?.postCreated ?? '',
    offlineSavedTitle: t?.offlineSaved ?? '',
    confirm: t?.confirm ?? '',
    cancel: t?.cancel ?? '',
    writeWebNovel: t?.writeWebNovel ?? '',
    posting: t?.loading ?? '',
    post: t?.publish ?? '',
    webNovelBody: t?.autoGeneratedContent ?? '',
    postTitle: t?.postTitleLabel ?? t?.title ?? '',
    authorNote: t?.authorNote ?? t?.description ?? '',
    introPlaceholder: t?.novelIntroPlaceholder ?? '',
    tagsMax: t?.tagsMax5 ?? '',
    addTag: t?.addTag ?? '',
    goCommunity: t?.goToCommunity ?? t?.community ?? '',
    viewWebNovel: t?.viewWebnovelBtn ?? t?.webnovelTag ?? '',
    communityPosted: t?.communityPosted ?? ''
  };

  const addTag = useCallback(() => {
    const trimmed = tagInput.trim();
    if (trimmed && tags.length < 5 && !tags.includes(trimmed)) {
      setTags(previous => [...previous, trimmed]);
      setTagInput('');
    }
  }, [tagInput, tags]);

  const handlePost = useCallback(async () => {
    if (!title.trim()) {
      ToastService.error(labels.titleRequired);
      return;
    }
    if (!content.trim()) {
      ToastService.error(labels.contentRequired);
      return;
    }

    buttonScale.value = withSequence(
      withSpring(0.92, { damping: 20, stiffness: 500 }),
      withSpring(1.04, { damping: 14, stiffness: 300 }),
      withSpring(1, { damping: 12, stiffness: 280 }),
    );

    setPosting(true);
    try {
      const novel = getWebNovel(novelId ?? '');
      const authorId = user?.id ?? '';
      const authorName = user?.name ?? user?.email ?? t?.authorFallback ?? '';
      const authToken = user?.jwtToken ?? '';

      const result = await NovelAPI.createPost(
        {
          title: title.trim(),
          content: content.trim(),
          tags,
          novelPreview,
          novelBody: novel?.paragraphs ?? [],
          emotionData: novel?.emotionData ?? {},
          characters: novel?.characters ?? [],
          authorId,
          authorName,
          lang: currentLanguage ?? 'en'
  },
        authToken,
      );

      if (result) {
        ToastService.success(labels.postSuccess);
        if (isMountedRef.current) {
          setPostedNovelId(novelId ?? '');
          setPosted(true);
        }
      } else {
        saveCommunityNovelPost({
          novelId: novelId ?? '',
          title: title.trim(),
          content: content.trim(),
          novelPreview,
          authorName,
          authorId,
          tags,
          boardType: 'webnovel',
          lang: currentLanguage ?? 'en' });

        ToastService.success(labels.offlineSavedTitle);
      }
    } catch {
      ToastService.error(labels.postFailed);
    } finally {
      if (isMountedRef.current) {
        setPosting(false);
      }
    }
  }, [
    buttonScale,
    content,
    currentLanguage,
    labels.contentRequired,
    labels.offlineSavedTitle,
    labels.postFailed,
    labels.postSuccess,
    labels.titleRequired,
    novelId,
    novelPreview,
    tags,
    title,
    user,
  ]);

  if (posted) {
    return (
      <View style={styles.root}>
        <PremiumBackdrop animated />
        <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
        <Animated.View entering={FadeIn.duration(330)} style={[styles.postedContainer, { paddingTop: insets.top + 32, paddingBottom: insets.bottom + 24 }]}>
          <CheckCircle size={56} color={'#D4A853'} style={styles._marginBottom} />
          <Text style={styles.postedTitle}>{title}</Text>
          <Text style={styles.postedSub}>{labels.communityPosted}</Text>

          <TouchableOpacity
            activeOpacity={1}
            style={styles.viewNovelButton}
            onPress={() => navigation.navigate('WebNovelReader', { novelId: postedNovelId })}
          >
            <BookOpen size={22} color={'#050507'} />
            <Text style={styles.viewNovelButtonText}>{labels.viewWebNovel}</Text>
          </TouchableOpacity>

          <TouchableOpacity
            activeOpacity={1}
            style={styles.goCommunityButton}
            onPress={() => (navigation as any).navigate('Main', { screen: 'Community' })}
          >
            <Text style={styles.goCommunityText}>{labels.goCommunity}</Text>
          </TouchableOpacity>
        </Animated.View>
      </View>
    );
  }

  return (
    <View style={styles.root}>
      <PremiumBackdrop animated />
      <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />

      <Animated.View entering={FadeIn.duration(260)} style={[styles.header, { paddingTop: insets.top }]}>
        <TouchableOpacity activeOpacity={1} onPress={() => navigation.goBack()} style={styles.headerSide}>
          <Text style={styles.cancelText}>{labels.cancel}</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{labels.writeWebNovel}</Text>
        <TouchableOpacity activeOpacity={1} onPress={handlePost} style={styles.headerSide} disabled={posting}>
          <Animated.View style={buttonStyle}>
            <Text style={[styles.postText, posting && styles.postTextDisabled]}>{posting ? labels.posting : labels.post}</Text>
          </Animated.View>
        </TouchableOpacity>
      </Animated.View>

      <KeyboardAwareScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: insets.bottom + 32 }]}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        <View style={styles._marginBottom1}>
          <PremiumHeroCard
            eyebrow={t?.novelPublishEyebrow ?? labels.writeWebNovel}
            title={title.trim() || labels.writeWebNovel}
            subtitle={novelPreview || labels.introPlaceholder}
            icon={BookOpen}
            pills={[
              `${tags.length}/5 ${t?.tags ?? t?.editorHashtag ?? ''}`,
              novelId ? (t?.pillLinkedSource ?? '') : (t?.pillStandalone ?? ''),
              currentLanguage ?? 'en',
            ]}
          />
        </View>
        <Animated.View entering={FadeInDown.delay(60).springify().damping(22)} style={styles.previewCard}>
          <View style={styles.previewIconRow}>
            <BookOpen size={16} color={'#D4A853'} />
            <Text style={styles.previewLabel}>{labels.webNovelBody}</Text>
          </View>
          <Text style={styles.previewTitle} numberOfLines={1}>{novelTitle ?? (t?.webnovelTag ?? '')}</Text>
          {!!novelPreview && <Text style={styles.previewBody} numberOfLines={5}>{novelPreview}</Text>}
        </Animated.View>

        <Animated.View entering={FadeInDown.delay(120).springify().damping(22)}>
          <Text style={styles.fieldLabel}>{labels.postTitle}</Text>
          <AnimatedInput placeholder={labels.postTitle} value={title} onChangeText={setTitle} maxLength={100} style={styles.titleStyle} />
        </Animated.View>

        <Animated.View entering={FadeInDown.delay(180).springify().damping(22)} style={[styles.flex1, { minHeight: 400 }]}>
          <Text style={styles.fieldLabel}>{t?.novelContent ?? ''}</Text>
          <NovelEditor initialContent={content} onSave={setContent} />
        </Animated.View>

        <Animated.View entering={FadeInDown.delay(240).springify().damping(22)}>
          <Text style={styles.fieldLabel}>{labels.tagsMax}</Text>
          <View style={styles.tagRow}>
            <AnimatedInput
              placeholder={labels.addTag}
              value={tagInput}
              onChangeText={setTagInput}
              onSubmitEditing={addTag}
              maxLength={20}
              containerStyle={styles.flex1}
              style={styles.tagInputStyle}
            />
            <TouchableOpacity activeOpacity={1} style={styles.addTagButton} onPress={addTag}>
              <Text style={styles.addTagText}>+</Text>
            </TouchableOpacity>
          </View>

          {tags.length > 0 && (
            <View style={styles.tagList}>
              {tags.map((tag, index) => (
                <Animated.View key={`${tag}_${index}`} entering={FadeInDown.delay(index * 40).springify().damping(20)} style={styles.tagChip}>
                  <Text style={styles.tagChipText}>{tag}</Text>
                  <TouchableOpacity activeOpacity={1} onPress={() => setTags(previous => previous.filter((_, i) => i !== index))}>
                    <Text style={styles.tagRemove}>×</Text>
                  </TouchableOpacity>
                </Animated.View>
              ))}
            </View>
          )}
        </Animated.View>
      </KeyboardAwareScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  flex1: { flex: 1 },
  root: { flex: 1, backgroundColor: '#050507' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Space['4'],
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#1A1A24'
  },
  headerSide: { width: 78 },
  headerTitle: {
    fontSize: Typo.size.lg,
    fontFamily: Typography.fontFamily.bold,
    color: '#F0F0F5',
    textAlign: 'center'
  },
  cancelText: { fontSize: Typo.size.base, color: '#8A8A9E' },
  postText: { fontSize: Typo.size.base, color: '#D4A853', fontFamily: Typography.fontFamily.bold, textAlign: 'right' },
  postTextDisabled: { opacity: 0.4 },

  scroll: { flex: 1 },
  scrollContent: { padding: Space['4'], gap: Space['4'] },

  previewCard: {
    backgroundColor: '#0C0C14',
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(212,168,83,0.30)',
    padding: 14,
    gap: 6
  },
  previewIconRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  previewLabel: { fontSize: Typo.size.xs, color: '#D4A853', fontFamily: Typography.fontFamily.semibold },
  previewTitle: { fontSize: Typo.size.md, fontFamily: Typography.fontFamily.bold, color: '#F0F0F5' },
  previewBody: { fontSize: Typo.size.sm, color: '#8A8A9E', lineHeight: 20, fontStyle: 'italic' },

  fieldLabel: { fontSize: Typo.size.sm, color: '#8A8A9E', fontFamily: Typography.fontFamily.semibold, marginBottom: 6 },

  inputWrap: {
    backgroundColor: '#0C0C14',
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    borderColor: '#1A1A24',
    overflow: 'hidden'
  },
  inputInner: { padding: 14, color: '#F0F0F5' },
  titleStyle: { fontSize: Typo.size.md, fontFamily: Typography.fontFamily.semibold },
  contentStyle: { fontSize: Typo.size.base, minHeight: 140 },
  tagInputStyle: { fontSize: Typo.size.sm },

  tagRow: { flexDirection: 'row', gap: 8 },
  addTagButton: {
    width: 48,
    height: 48,
    backgroundColor: '#0C0C14',
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#1A1A24'
  },
  addTagText: { fontSize: 24, color: '#F0F0F5' },

  tagList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(212,168,83,0.14)',
    borderRadius: Radius.full,
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 5,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(212,168,83,0.30)'
  },
  tagChipText: { fontSize: Typo.size.xs, color: '#D4A853' },
  tagRemove: { fontSize: 16, color: '#D4A853', fontFamily: Typography.fontFamily.bold },

  postedContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    gap: 12
  },
  postedTitle: {
    fontSize: Typo.size.xl,
    fontFamily: Typography.fontFamily.bold,
    color: '#F0F0F5',
    textAlign: 'center',
    lineHeight: 28,
    marginBottom: 4
  },
  postedSub: {
    fontSize: Typo.size.md,
    color: '#8A8A9E',
    textAlign: 'center',
    marginBottom: 24
  },
  viewNovelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#D4A853',
    borderRadius: Radius.xl,
    paddingVertical: 18,
    paddingHorizontal: 40,
    width: '100%',
    elevation: 6
  },
  viewNovelButtonText: { fontSize: Typo.size.lg, fontFamily: Typography.fontFamily.bold, color: '#050507' },

  goCommunityButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: '#1A1A24',
    width: '100%',
    alignItems: 'center',
    marginTop: 4
  },
  goCommunityText: { fontSize: Typo.size.base, color: '#8A8A9E', fontFamily: Typography.fontFamily.medium },
  _marginBottom: {
    marginBottom: 16
  },
  _marginBottom1: {
    marginBottom: 18
  }
  });
